### ISSUE TITLE
(IN PROGRESS) Manually make embeddings using GCP + Jupyter notebook

### ISSUE THREAD

**Issue by justaddcoffee** [Knowledge-Graph-Hub/kg-ontoml#10]

**Comment by caufieldjh** [comment]
Now available - SkipGram on KG-OntoML build [20220304](https://kg-hub.berkeleybop.io/kg-ontoml/20220304)
https://kg-hub.berkeleybop.io/kg-ontoml/graphml/KG-OntoML-SkipGram-Mar_11_2022.tar.gz
